{
 "title": "Bitovi's expanded dashboard",
 "tags": [
  "temporal",
  "bitovi"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Welcome",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard was created by Bitovi and applied via the API."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Service Availability Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Service Availability",
   "type": "stat",
   "description": "Overall % of successful gRPC requests using time range specified (all services). Useful to monitor cluster health.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (sum(rate(service_errors[$__range]) OR on() vector(0)) / sum(rate(service_requests[$__range])) * 100)",
     "legendFormat": "Availability"
    }
   ]
  },
  {
   "title": "Persistence Service Success %",
   "type": "stat",
   "description": "Percentage of successful requests to the persistence service in the time range selected (cluster-wide).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (sum(rate(persistence_errors[$__range]) OR on() vector(0)) / sum(rate(persistence_requests[$__range])) * 100)",
     "legendFormat": "Success %"
    }
   ]
  },
  {
   "title": "Resource exhaustion by namespace, cause and servicename",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (namespace, resource_exhausted_cause, service_name) (rate(service_errors_resource_exhausted{}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State Transition Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(state_transition_count_count{namespace!=\"temporal_system\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Errors by Type (frontend)",
   "type": "bargauge",
   "description": "Number of errors by type for service_name=\"frontend\" in the time range selected.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(service_error_with_type{service_name=\"frontend\"}[$__range])) by (error_type)",
     "legendFormat": "{{error_type}}"
    }
   ]
  },
  {
   "title": "Service Errors by Type (history)",
   "type": "bargauge",
   "description": "Number of errors by type for service_name=\"history\" in the time range selected.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(service_error_with_type{service_name=\"history\"}[$__range])) by (error_type)",
     "legendFormat": "{{error_type}}"
    }
   ]
  },
  {
   "title": "Service Errors by Type (matching)",
   "type": "bargauge",
   "description": "Number of errors by type for service_name=\"matching\" in the time range selected..",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(service_error_with_type{service_name=\"matching\"}[$__range])) by (error_type)",
     "legendFormat": "{{error_type}}"
    }
   ]
  },
  {
   "title": "Service Errors by Type (worker)",
   "type": "bargauge",
   "description": "Number of errors by type for service_name=\"worker\" in the time range selected..",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(service_error_with_type{service_name=\"worker\"}[$__range])) by (error_type)",
     "legendFormat": "{{error_type}}"
    }
   ]
  },
  {
   "title": "Service Errors Break Down ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (service_name, resource_exhausted_cause) (rate(service_errors_entity_not_found[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (service_name, resource_exhausted_cause) (rate(service_errors_execution_already_started[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (service_name, resource_exhausted_cause) (rate(service_errors_resource_exhausted[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Persistence Service Performance Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Persistence Requests by Operation (Trend 5m Rate)",
   "type": "timeseries",
   "description": "Trend of persistence requests per operation in the time range selected. (cluster load over time per operation).",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(persistence_requests[5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Persistence Requests by Operation (5m Rate Total)",
   "type": "gauge",
   "description": "The number of persistence requests over the time range selected., grouped by cluster operation.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (operation) (increase(persistence_requests[5m])) > 50",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Service Performance Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {}
   ]
  },
  {
   "title": "95th Percentile Latency by Operation (frontend)",
   "type": "timeseries",
   "description": "The 95th percentile latency of gRPC calls to the 'frontend' service, grouped by operation over the time range selected. Substitute another service_name as needed.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(service_latency_bucket{service_name=\"frontend\"}[$__range])) by (operation, le))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "95th Percentile Latency by Operation (matching)",
   "type": "timeseries",
   "description": "The 95th percentile latency of gRPC calls to the 'frontend' service, grouped by operation over the time range selected. Substitute another service_name as needed.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(service_latency_bucket{service_name=\"matching\"}[$__range])) by (operation, le))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "95th Percentile Latency by Operation (history)",
   "type": "timeseries",
   "description": "The 95th percentile latency of gRPC calls to the 'frontend' service, grouped by operation over the time range selected. Substitute another service_name as needed.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(service_latency_bucket{service_name=\"history\"}[$__range])) by (operation, le))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "External Event Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {}
   ]
  },
  {
   "title": "External Events: Workflow & Signal Requests",
   "type": "timeseries",
   "description": "The number of gRPC requests coming into the cluster from external clients (start workflows or signals) during the time range selected.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(service_requests{operation=~\"StartWorkflowExecution|SignalWorkflowExecution|SignalWithStartWorkflowExecution\"}[$__range]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Workflow Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 },
   "targets": [
    {}
   ]
  },
  {
   "title": "AddWorkflowTask Requests (rate)",
   "type": "stat",
   "description": "The number of gRPC requests to add new workflows in the time range selected. Monitor with 'RecordWorkflowTaskStarted', 'RespondWorkflowTaskCompleted', and 'RespondWorkflowTaskFailed' to observe expected state transitions.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(service_requests{ operation=\"AddWorkflowTask\"}[$__range]))",
     "legendFormat": "AddWorkflowTask"
    }
   ]
  },
  {
   "title": "ScheduleToStart Timeout (rate)",
   "type": "stat",
   "description": "The number of workflows in the time range selected that exceeded maximum schedule-to-start timeout. Indicates if workers are busy or unavailable.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(schedule_to_start_timeout{ operation=\"TimerActiveTaskWorkflowTimeout\"}[$__range]))",
     "legendFormat": "ScheduleToStartTimeout"
    }
   ]
  },
  {
   "title": "ScheduleToClose Timeout (rate)",
   "type": "stat",
   "description": "The number of workflows in the time range selected that exceeded schedule-to-close timeout. Indicates workflows may not be completing due to slowdowns.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(start_to_close_timeout{ operation=\"TimerActiveTaskWorkflowTimeout\"}[$__range]))",
     "legendFormat": "ScheduleToCloseTimeout"
    }
   ]
  },
  {
   "title": "History Cache Lock Latency (p99)",
   "type": "timeseries",
   "description": "The 99th percentile lock acquisition latency for workflow history ('HistoryCacheGetOrCreate') during the time range selected. Shows lock impact on workflow progress.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(cache_latency_bucket{operation=\"HistoryCacheGetOrCreate\"}[$__range])) by (le))",
     "legendFormat": "p99 history cache lock"
    }
   ]
  },
  {
   "title": "Shard Lock Latency (p99)",
   "type": "timeseries",
   "description": "The 99th percentile lock acquisition latency for workflow history shards ('ShardInfo') during the time range selected. Shows lock impact on workflow progress.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(lock_latency_bucket{operation=\"ShardInfo\"}[$__range])) by (le))",
     "legendFormat": "p99 shard lock"
    }
   ]
  },
  {
   "title": "Activity Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 },
   "targets": [
    {}
   ]
  },
  {
   "title": "AddActivityTask Requests (rate)",
   "type": "stat",
   "description": "The number of gRPC requests to add new activities in the time range selected. Useful to monitor initiation of activities.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(service_requests{operation=\"AddActivityTask\"}[$__range]))",
     "legendFormat": "AddActivityTask"
    }
   ]
  },
  {
   "title": "RecordActivityTaskStarted Requests (rate)",
   "type": "stat",
   "description": "The number of gRPC requests recording the start of an activity in the time range selected. Monitor against the previous panel to represent latency between scheduling and execution.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(service_requests{operation=\"RecordActivityTaskStarted\"}[$__range]))",
     "legendFormat": "RecordActivityTaskStarted"
    }
   ]
  },
  {
   "title": "ActivityTask End Requests (rate)",
   "type": "stat",
   "description": "The number of gRPC requests recording the end of an activity in the time range selected. Monitor against the previous panel to represent completion latency.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(service_requests{operation=~\"RespondActivityTaskCompleted|RespondActivityTaskFailed|RespondActivityTaskCanceled\"}[$__range]))",
     "legendFormat": "ActivityTask Completed/Failed/Canceled"
    }
   ]
  },
  {
   "title": "Service Health Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Service Restarts",
   "type": "bargauge",
   "description": "The number of cluster service restarts, grouped by service, in the time range selected. Frequent restarts indicate underlying issues.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (temporal_service_type) (increase(restarts[$__range]))",
     "legendFormat": "{{temporal_service_type}}"
    }
   ]
  },
  {
   "title": "Resource Exhausted Errors",
   "type": "bargauge",
   "description": "The number of 'resource exhausted' errors, grouped by cause, during the time range selected. Indicates rate limits/system overload.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(service_errors_resource_exhausted{}[$__range])) by (resource_exhausted_cause)",
     "legendFormat": "{{resource_exhausted_cause}}"
    }
   ]
  },
  {
   "title": "State Transition Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 },
   "targets": [
    {}
   ]
  },
  {
   "title": "State Transitions (rate)",
   "type": "stat",
   "description": "The number of state transitions persisted to the database in the time range selected. Indicates cluster throughput.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(state_transition_count[$__range]))",
     "legendFormat": "StateTransitions"
    }
   ]
  },
  {
   "title": "Shard Rebalancing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 134 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Shard Rebalances (rate)",
   "type": "stat",
   "description": "Number of History shard rebalances in the time range selected. Frequent rebalancing not due to scaling may indicate node issues.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(membership_changed_count[$__range]))",
     "legendFormat": "ShardRebalances"
    }
   ]
  },
  {
   "title": "Worker Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 141 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Available Worker Task Slots (avg over time)",
   "type": "stat",
   "description": "Average number of worker task slots available for WorkflowWorker in the time range selected. Hitting zero indicates worker backlog.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(temporal_worker_task_slots_available{namespace=\"default\",worker_type=\"WorkflowWorker\"}[$__range])",
     "legendFormat": "Slots Available"
    }
   ]
  },
  {
   "title": "Workflow Task Schedule-to-Start Latency",
   "type": "timeseries",
   "description": "Latency from when a workflow task enters the queue to when a worker picks it up in the time range selected. Monitor per namespace and task queue.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (namespace, task_queue) (rate(temporal_workflow_task_schedule_to_start_latency_seconds_bucket[$__range]))",
     "legendFormat": "{{namespace}}:{{task_queue}}"
    }
   ]
  },
  {
   "title": "Activity Task Schedule-to-Start Latency",
   "type": "timeseries",
   "description": "Latency from when an activity task enters the queue to when a worker picks it up in the time range selected. Monitor per namespace and task queue.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (namespace, task_queue) (rate(temporal_activity_schedule_to_start_latency_seconds_bucket[$__range]))",
     "legendFormat": "{{namespace}}:{{task_queue}}"
    }
   ]
  },
  {
   "title": "Sync Match Rate",
   "type": "stat",
   "description": "The 'sync match rate' between workers and matching service during the time range selected. High rates reduce task latency and persistence load.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(poll_success_sync{}[$__range])) / sum(rate(poll_success{}[$__range]))",
     "legendFormat": "SyncMatchRate"
    }
   ]
  }
 ]
}