{
 "title": "Bitovi's expanded dashboard",
 "tags": [
  "temporal",
  "bitovi"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Node",
    "query": "bitovi-mk8s2-node1, bitovi-mk8s2-node2"
   }
  ]
 },
 "panels": [
  {
   "title": "Persistence Service Performance Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Persistence Requests by Operation (Trend 5m Rate)",
     "type": "timeseries",
     "description": "This shows the per-node request throughput to the Temporal persistence layer, broken down by operation. It helps identify which operations (e.g., history appends, workflow updates, replication tasks) are driving backend load on each node, useful for spotting hot nodes, spikes, or replication-related pressure in multi-cluster setups.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (operation, node) (rate(persistence_requests{node=\"${Node}\"}[2m]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Persistence Requests by Operation (5m Rate Total)",
     "type": "gauge",
     "description": "The number of persistence requests over the time range selected., grouped by cluster operation.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (operation) (increase(persistence_requests{node=\"${Node}\"}[2m])) > 50",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Shard Lock Latency (p99)",
     "type": "timeseries",
     "description": "The 99th percentile lock acquisition latency for workflow history shards ('ShardInfo') during the time range selected. Shows lock impact on workflow progress.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(lock_latency_bucket{node=\"${Node}\", operation=\"ShardInfo\"}[2m])) by (le))",
       "legendFormat": "p99 shard lock"
      }
     ]
    },
    {
     "title": "History Cache Lock Latency (p99)",
     "type": "timeseries",
     "description": "The 99th percentile lock acquisition latency for workflow history ('HistoryCacheGetOrCreate') during the time range selected. Shows lock impact on workflow progress.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(cache_latency_bucket{node=\"${Node}\", operation=\"HistoryCacheGetOrCreate\"}[2m])) by (le))",
       "legendFormat": "p99 history cache lock"
      }
     ]
    }
   ]
  },
  {
   "title": "Activity Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "AddActivityTask Requests (rate)",
     "type": "stat",
     "description": "The number of gRPC requests to add new activities in the time range selected. Useful to monitor initiation of activities.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(service_requests{node=\"${Node}\", operation=\"AddActivityTask\"}[$__range]))",
       "legendFormat": "AddActivityTask"
      }
     ]
    },
    {
     "title": "RecordActivityTaskStarted Requests (rate)",
     "type": "stat",
     "description": "The number of gRPC requests recording the start of an activity in the time range selected. Monitor against the previous panel to represent latency between scheduling and execution.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(service_requests{node=\"${Node}\", operation=\"RecordActivityTaskStarted\"}[$__range]))",
       "legendFormat": "RecordActivityTaskStarted"
      }
     ]
    },
    {
     "title": "ActivityTask End Requests (rate)",
     "type": "stat",
     "description": "The number of gRPC requests recording the end of an activity in the time range selected. Monitor against the previous panel to represent completion latency.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(service_requests{node=\"${Node}\", operation=~\"RespondActivityTaskCompleted|RespondActivityTaskFailed|RespondActivityTaskCanceled\"}[$__range]))",
       "legendFormat": "ActivityTask Completed/Failed/Canceled"
      }
     ]
    }
   ]
  },
  {
   "title": "Service Availability Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service Availability",
     "type": "stat",
     "description": "Overall % of successful gRPC requests using time range specified (all services). Useful to monitor cluster health.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (sum(rate(service_errors{node=\"${Node}\"}[$__range]) OR on() vector(0)) / sum(rate(service_requests{node=\"${Node}\"}[$__range])) * 100)",
       "legendFormat": "Availability"
      }
     ]
    },
    {
     "title": "Persistence Service Success %",
     "type": "stat",
     "description": "Percentage of successful requests to the persistence service in the time range selected (cluster-wide).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (sum(rate(persistence_errors{node=\"${Node}\"}[$__range]) OR on() vector(0)) / sum(rate(persistence_requests{node=\"${Node}\"}[$__range])) * 100)",
       "legendFormat": "Success %"
      }
     ]
    },
    {
     "title": "Service Errors by Type (frontend)",
     "type": "bargauge",
     "description": "Number of errors by type for service_name=\"frontend\" in the time range selected.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(service_error_with_type{service_name=\"frontend\", node=\"${Node}\"}[5m])) by (error_type) > 10",
       "legendFormat": "{{error_type}}"
      }
     ]
    },
    {
     "title": "Service Errors by Type (history)",
     "type": "bargauge",
     "description": "Number of errors by type for service_name=\"history\" in the time range selected.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(service_error_with_type{service_name=\"history\", node=\"${Node}\"}[5m])) by (error_type) > 10",
       "legendFormat": "{{error_type}}"
      }
     ]
    },
    {
     "title": "Service Errors by Type (matching)",
     "type": "bargauge",
     "description": "Number of errors by type for service_name=\"matching\" in the time range selected..",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(service_error_with_type{service_name=\"matching\", node=\"${Node}\"}[$__range])) by (error_type)",
       "legendFormat": "{{error_type}}"
      }
     ]
    },
    {
     "title": "Service Errors by Type (worker)",
     "type": "bargauge",
     "description": "Number of errors by type for service_name=\"worker\" in the time range selected..",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(service_error_with_type{service_name=\"worker\", node=\"${Node}\"}[$__range])) by (error_type)",
       "legendFormat": "{{error_type}}"
      }
     ]
    },
    {
     "title": "Resource exhaustion by namespace, cause and servicename",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
     "targets": [
      {
       "expr": "sum by (exported_namespace, resource_exhausted_cause, service_name) (rate(service_errors_resource_exhausted{node=\"${Node}\"}[2m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Service Errors Break Down ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (service_name, resource_exhausted_cause) (rate(service_errors_entity_not_found{node=\"${Node}\"}[2m]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (service_name, resource_exhausted_cause) (rate(service_errors_execution_already_started{node=\"${Node}\"}[2m]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (service_name, resource_exhausted_cause) (rate(service_errors_resource_exhausted{node=\"${Node}\"}[2m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "latency for HistoryCacheGetOrCreate operation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(cache_latency_bucket{operation=\"HistoryCacheGetOrCreate\"}[2m])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Service Performance Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "95th Percentile Latency by Operation (frontend)",
     "type": "timeseries",
     "description": "The 95th percentile latency of gRPC calls to the 'frontend' service, grouped by operation over the time range selected. Substitute another service_name as needed.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(service_latency_bucket{service_name=\"frontend\", node=\"${Node}\"}[2m])) by (operation, le))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "95th Percentile Latency by Operation (matching)",
     "type": "timeseries",
     "description": "The 95th percentile latency of gRPC calls to the 'frontend' service, grouped by operation over the time range selected. Substitute another service_name as needed.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(service_latency_bucket{service_name=\"matching\", node=\"${Node}\"}[$__range])) by (operation, le))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "95th Percentile Latency by Operation (history)",
     "type": "timeseries",
     "description": "The 95th percentile latency of gRPC calls to the 'frontend' service, grouped by operation over the time range selected. Substitute another service_name as needed.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(service_latency_bucket{service_name=\"history\", node=\"${Node}\"}[$__range])) by (operation, le))",
       "legendFormat": "{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "External Event Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "External Events: Workflow & Signal Requests",
     "type": "timeseries",
     "description": "The number of gRPC requests coming into the cluster from external clients (start workflows or signals) during the time range selected.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (operation) (rate(service_requests{node=\"${Node}\", operation=~\"StartWorkflowExecution|SignalWorkflowExecution|SignalWithStartWorkflowExecution\"}[$__range]))",
       "legendFormat": "{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Workflow Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "AddWorkflowTask Requests (rate)",
     "type": "stat",
     "description": "The number of gRPC requests to add new workflows in the time range selected. Monitor with 'RecordWorkflowTaskStarted', 'RespondWorkflowTaskCompleted', and 'RespondWorkflowTaskFailed' to observe expected state transitions.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(service_requests{node=\"${Node}\", operation=\"AddWorkflowTask\"}[$__range]))",
       "legendFormat": "AddWorkflowTask"
      }
     ]
    },
    {
     "title": "ScheduleToStart Timeout (rate)",
     "type": "stat",
     "description": "The number of workflows in the time range selected that exceeded maximum schedule-to-start timeout. Indicates if workers are busy or unavailable.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(schedule_to_start_timeout{node=\"${Node}\", operation=\"TimerActiveTaskWorkflowTimeout\"}[$__range]))",
       "legendFormat": "ScheduleToStartTimeout"
      }
     ]
    },
    {
     "title": "ScheduleToClose Timeout (rate)",
     "type": "stat",
     "description": "The number of workflows in the time range selected that exceeded schedule-to-close timeout. Indicates workflows may not be completing due to slowdowns.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(start_to_close_timeout{node=\"${Node}\", operation=\"TimerActiveTaskWorkflowTimeout\"}[$__range]))",
       "legendFormat": "ScheduleToCloseTimeout"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Access",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service Requests (by namespace)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum by (service_name, namespace) (rate(service_requests{node=\"${Node}\", service_name=\"frontend\", app_kubernetes_io_headless=\"\", namespace=~\"${namespace}\"}[2m])) * 120",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (service_name, namespace)  (rate(service_requests{node=\"${Node}\", service_name=\"history\", app_kubernetes_io_headless=\"\", namespace=~\"${namespace}\"}[2m])) * 120",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Service Errors (by namespace)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "sum by (service_name) (rate(service_errors{service_name=\"frontend\", app_kubernetes_io_headless=\"\", namespace=~\"${namespace}\", node=\"${Node}\"}[2m])) ",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (service_name) (rate(service_errors{service_name=\"history\", app_kubernetes_io_headless=\"\", namespace=~\"${namespace}\", node=\"${Node}\"}[2m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "API Latencies (Frontend)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (operation, le) (rate(service_latency_bucket{operation=~\"StartWorkflowExecution|SignalWorkflowExecution|RespondWorkflowTaskCompleted|RespondActivityTaskCompleted\", service_name=\"frontend\", node=\"${Node}\"}[2m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "API Latencies (History)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (operation, le) (rate(service_latency_bucket{operation=~\"StartWorkflowExecution|SignalWorkflowExecution|RespondWorkflowTaskCompleted|RespondActivityTaskCompleted\", service_name=\"history\", node=\"${Node}\"}[2m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pending Requests per namespace and operation (Frontend)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "sum by (namespace, operation) (service_pending_requests{node=\"${Node}\", service_name=\"frontend\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Client Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "client_errors per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "err/s" } },
     "targets": [
      {
       "expr": "sum by (operation, error_type) (rate(client_errors{service_name=\"frontend\",service_role=\"history\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sum of CreateTasks (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "sum(rate(persistence_requests{node=\"${Node}\", operation=\"CreateTask\"}[2m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Schedule to Start Latency (Per operation/namespace/type)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95,\n  sum by (namespace, task_type, operation, le) (rate(task_schedule_to_start_latency_bucket{namespace=~\"${namespace}\", node=\"${Node}\"}[2m]))\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sum of Start to Close timeouts (5m)",
     "type": "timeseries",
     "description": "Rate of timeouts over 2 minute ranges",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (namespace, operation) (rate(start_to_close_timeout{operation=\"TimerActiveTaskWorkflowTaskTimeout\", node=\"${Node}\"}[2m]))",
       "legendFormat": "__auto"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "per-workflow-lock latency (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99,\nsum by (le)(rate(cache_latency_bucket{node=\"${Node}\", operation=\"HistoryCacheGetOrCreate\"}[2m]))\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Service Health Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temporal Services Cores Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum by (container)(rate(container_cpu_usage_seconds_total{node=\"${Node}\", container=\"temporal-history\"}[2m]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (container)(rate(container_cpu_usage_seconds_total{container=\"temporal-frontend\"}[2m]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (container)(rate(container_cpu_usage_seconds_total{node=\"${Node}\", container=\"temporal-matching\"}[2m]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (container)(rate(container_cpu_usage_seconds_total{node=\"${Node}\", container=\"temporal-worker\"}[2m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Temporal Services Memory used (MiB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "sum by (container) (container_memory_usage_bytes{node=\"${Node}\", container=\"temporal-frontend\"}) / 1024 / 1024",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (container) (container_memory_usage_bytes{container=\"temporal-history\"}) / 1024 / 1024",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (container) (container_memory_usage_bytes{node=\"${Node}\", container=\"temporal-matching\"}) / 1024 / 1024",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (container) (container_memory_usage_bytes{node=\"${Node}\", container=\"temporal-worker\"}) / 1024 / 1024",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cluster Service Restarts",
     "type": "bargauge",
     "description": "The number of cluster service restarts, grouped by service, in the time range selected. Frequent restarts indicate underlying issues.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (temporal_service_type) (increase(restarts{node=\"${Node}\"}[$__range]))",
       "legendFormat": "{{temporal_service_type}}"
      }
     ]
    },
    {
     "title": "Resource Exhausted Errors",
     "type": "bargauge",
     "description": "The number of 'resource exhausted' errors, grouped by cause, during the time range selected. Indicates rate limits/system overload.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(service_errors_resource_exhausted{node=\"${Node}\"}[2m])) by (resource_exhausted_cause)",
       "legendFormat": "{{resource_exhausted_cause}}"
      }
     ]
    }
   ]
  },
  {
   "title": "State Transition Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "State Transitions (rate)",
     "type": "timeseries",
     "description": "The number of state transitions persisted to the database in the time range selected. Indicates cluster throughput.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (namespace) (rate(state_transition_count_count{node=\"${Node}\", namespace!=\"temporal_system\"}[2m]))",
       "legendFormat": "StateTransitions"
      }
     ]
    },
    {
     "title": "Persistence Requests (Create|Update)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "sum by (operation) (rate(persistence_requests{node=\"${Node}\", operation=~\"CreateWorkflowExecution|UpdateWorkflowExecution\"}[2m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Persistence Requests (all operations)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "sum by (operation) (rate(persistence_requests{node=\"${Node}\"}[2m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Persistence Requests (total)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "expr": "sum (rate(persistence_requests{node=\"${Node}\"}[2m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "History Shards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Shard Rebalances (rate)",
     "type": "timeseries",
     "description": "Number of History shard rebalances in the time range selected. Frequent rebalancing not due to scaling may indicate node issues.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(membership_changed_count{node=\"${Node}\"}[2m])) *120",
       "legendFormat": "ShardRebalances"
      },
      {
       "expr": "sum(rate(sharditem_created_count{node=\"${Node}\"}[2m]))*120",
       "legendFormat": "Shard Created"
      }
     ]
    },
    {
     "title": "Shard distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "numshards_gauge{app_kubernetes_io_headless=\"\", node=\"${Node}\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Worker Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Available Worker Task Slots (avg over time)",
     "type": "stat",
     "description": "Average number of worker task slots available for WorkflowWorker in the time range selected. Hitting zero indicates worker backlog.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(temporal_worker_task_slots_available{namespace=\"default\",worker_type=\"WorkflowWorker\", node=\"${Node}\"}[$__range])",
       "legendFormat": "Slots Available"
      }
     ]
    },
    {
     "title": "Workflow Task Schedule-to-Start Latency",
     "type": "timeseries",
     "description": "Latency from when a workflow task enters the queue to when a worker picks it up in the time range selected. Monitor per namespace and task queue.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (namespace, task_queue) (rate(temporal_workflow_task_schedule_to_start_latency_seconds_bucket{node=\"${Node}\"}[$__range]))",
       "legendFormat": "{{namespace}}:{{task_queue}}"
      }
     ]
    },
    {
     "title": "Activity Task Schedule-to-Start Latency",
     "type": "timeseries",
     "description": "Latency from when an activity task enters the queue to when a worker picks it up in the time range selected. Monitor per namespace and task queue.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (namespace, task_queue) (rate(temporal_activity_schedule_to_start_latency_seconds_bucket{node=\"${Node}\"}[$__range]))",
       "legendFormat": "{{namespace}}:{{task_queue}}"
      }
     ]
    },
    {
     "title": "Sync Match Rate",
     "type": "stat",
     "description": "The 'sync match rate' between workers and matching service during the time range selected. High rates reduce task latency and persistence load.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(poll_success_sync{node=\"${Node}\"}[$__range])) / sum(rate(poll_success{node=\"${Node}\"}[$__range]))",
       "legendFormat": "SyncMatchRate"
      }
     ]
    }
   ]
  },
  {
   "title": "Visibility",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Visibility task end-to-end latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, \nsum(rate(task_latency_queue_bucket{node=\"${Node}\", operation=~\"VisibilityTask.*\", service_name=\"history\" }[2m])) by (operation, le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "95% Visibility Task Latency (2m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95,\nsum(rate(task_latency_bucket{node=\"${Node}\", operation=~\"VisibilityTask.*\", service_name=\"history\"}[2m])) by (operation, le)\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}