{
 "title": "Temporal Replication",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Average time for Replication",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(replication_latency_sum[5m]) / rate(replication_latency_count[2m])",
     "legendFormat": "Namespace: {{exported_namespace}}, Operation: {{operation}}, Source: {{source_cluster}}, Target: {{node}}"
    }
   ]
  },
  {
   "title": "95% Latency Source -> Target",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n0.95,\nsum by (le, source_cluster, node) (rate(replication_latency_bucket[2m]))\n)",
     "legendFormat": "{{source_cluster}} -> {{node}}"
    }
   ]
  },
  {
   "title": "95% Replication Latency",
   "type": "timeseries",
   "description": "The latency time of the lowest 95% of requests",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(replication_latency_bucket{}[2m])) by (operation, source_cluster, exported_namespace, node, le))",
     "legendFormat": "{{source_cluster}} -> {{node}}, Operation: {{operation}}"
    }
   ]
  }
 ]
}